name: CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: processor

      - name: Execute Gradle build
        run: ./gradlew build
        working-directory: processor

      - name: Execute Gradle Coverage
        run: ./gradlew check
        working-directory: processor
